---
title: "Plotting"
author: "Manoj"
date: "`r Sys.Date()`"
output: html_document
---

#Scatter plot

```{r}
x = 1:10
y = x^2
plot(x,y,type = "b", main = "Simple Plot", xlab ="X values", ylab="x^2")
```

# Histogram

```{r}
x = rbinom(100,10,0.6)
hist(x, main = "Histogram")
```


```{r}
x = rnorm(1000,10,0.6)
hist(x, main = "Histogram",breaks = 20,density = T)

```

```{r}
library(ggplot2)
ggplot(data = iris, aes(hwy))+
  geom_boxplot()
```

```{r}
ggplot(data = iris, aes(Sepal.Length,Petal.Length,color=Species,shape=Species))+
  geom_point()
```

```{r}
ggplot(data = iris, aes(Sepal.Length))+
  geom_density()
```
```{r}
ggplot(data = iris, aes(Sepal.Length,Species))+
  geom_boxplot()
```

```{r}
ggplot(data = iris,aes(Sepal.Length))+

  geom_density()
```

```{r}
x1=ggplot(mpg,aes(fl,fill=drv))
x1+geom_bar(position = "dodge")
```

```{r}
x1=ggplot(mpg,aes(fl,fill=drv))
x1+geom_bar(position="fill")+labs(x="fl_value",title = "Bar plot")
```
```{r}
x=c("Button","Pocket","Collar","Cuff")
y=c(4,9,16,24)
df=data.frame(x,y)
z=cumsum(y)
ggplot()+geom_col(aes(x,y))+geom_line(aes(x,z))
```